export const IMAGES = {
  splash: require('./icons/splash.png'),
  welcomeBg: require('./icons/welcomeBg.png'),
  eye: require('./icons/eye.png'),
  google: require('./icons/Google.png'),
  facebook: require('./icons/Facebook.png'),
  X: require('./icons/X.png'),
  AvatarIcon: require('./icons/AvatarIcon.png'),

  LoginBg: require('./icons/LoginBg.png'),
  create: require('./icons/create.png'),
  call: require('./icons/call.png'),
  chat: require('./icons/chat.png'),
  explore: require('./icons/explore.png'),
  setting: require('./icons/setting.jpg'),
  scifi: require('./icons/scifi.png'),
  adventure: require('./icons/adventure.png'),
  space: require('./icons/space.jpg'),
postImg : require('./icons/Post.png'),
postImg1 : require('./icons/post1.png'),
postImg2 : require('./icons/post2.png'),
postImg3 : require('./icons/post3.png'),
pfp: require('./icons/pfp.png'),
};
